name: quran_app
description: "Digital Qurâ€™an & Islamic Companion"

publish_to: 'none'

version: 3.0.8+29

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.1
  shared_preferences: ^2.2.3
  scrollable_positioned_list: ^0.3.8
  screenshot: ^3.0.0
  share_plus: ^12.0.0
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.0
  audioplayers: ^6.0.0
  provider: ^6.1.1
  url_launcher: ^6.2.6
  http: ^1.2.0
  geolocator: 13.0.2
  geocoding: ^3.0.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  dio: ^5.4.3+1
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  flutter_qiblah: ^3.1.0+1
  flutter_svg: ^2.0.7
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.3
  sqflite: ^2.4.2
  youtube_player_flutter: ^9.0.3
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  drift_dev: ^2.14.0
  build_runner: ^2.4.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/main_logo.png"
  adaptive_icon_foreground: assets/images/main_logo.png
  adaptive_icon_background: "#0A1A2F"
  macos:
    generate: true
    image_path: "assets/images/main_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/audio/audio_index.json
    - assets/database/quran.db
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: LPMQ
      fonts:
        - asset: assets/fonts/LPMQ.ttf
    - family: Uthmani
      fonts:
        - asset: assets/fonts/UthmanicHafs.otf